name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test:
    name: Test and Lint (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    services:
      qdrant:
        image: qdrant/qdrant:v1.11.9
        ports:
          - 6333:6333
        options: >-
          --health-cmd="wget -qO- http://localhost:6333/readyz || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=30

    env:
      QDRANT_URL: "http://localhost:6333"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install dev deps; adjust extras as your project needs
          pip install -e '.[dev]' || pip install -e .

      - name: Wait for Qdrant to be healthy
        run: |
          for i in {1..60}; do
            if curl -sf http://localhost:6333/readyz >/dev/null; then
              echo "Qdrant is ready"; exit 0
            fi
            sleep 1
          done
          echo "Qdrant failed to become ready"; exit 1

      - name: Lint with Ruff
        run: |
          ruff check . --output-format=github
          ruff format . --check

      - name: Run Tests
        run: |
          pytest -v --maxfail=1 --disable-warnings --cov=src --cov-report=term-missing

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [test]  # only build if tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Validate build with Twine
        run: |
          twine check dist/*

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
